apiVersion: apps/v1
kind: Deployment
metadata:
  name:  unicorn
spec:
  selector:
    matchLabels:
      name:  unicorn

  replicas:  1

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate

  template:
    metadata:
      labels:
        name:  unicorn

    spec:
      containers:
      - image:  fattymango/unicorn:unique
        name:  unicorn
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 90
        #   timeoutSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 5000
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 10
        env:
        - name:  PORT
          value:  "8080"  

        ports:
        - containerPort:  8080
          name:  http

        # volumeMounts:
        # - mountPath: /data
        #   name: data
      # volumes:
      #   - name: data
      #     emptyDir: {}

      restartPolicy: Always
  # imagePullPolicy: Always