apiVersion: v1
kind: Pod
metadata:
  name: unicorn
  labels:
    name: unicorn
spec:
  containers:
  - name: unicorn
    image: fattymango/unicorn:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: PORT
        value: "8080"
    ports:
      - containerPort: 8080
